# app/utils/common_icons.py

# Define event icons
event_icons = {
    # Existing event icons (payment, system, user, etc.)
    "payment.authorized": "💳",
    "payment.failed": "❌",
    "payment.captured": "✅",
    "payment.downtime.started": "⏳",
    "payment.downtime.updated": "🔄",
    "payment.downtime.resolved": "✔️",
    "order.paid": "💰",
    "order.notification.delivered": "📤",
    "order.notification.failed": "📭",
    "invoice.paid": "🧾",
    "invoice.partially_paid": "🔸",
    "invoice.expired": "⏳",
    "subscription.authenticated": "🔑",
    "subscription.paused": "⏸️",
    "subscription.resumed": "▶️",
    "subscription.activated": "⚡",
    "subscription.pending": "⏳",
    "subscription.halted": "❌",
    "subscription.charged": "💸",
    "subscription.cancelled": "❌",
    "subscription.completed": "✔️",
    "subscription.updated": "🔄",
    "settlement.processed": "💵",
    "virtual_account.credited": "💰",
    "virtual_account.created": "🎉",
    "virtual_account.closed": "🔒",
    "qr_code.closed": "🔒",
    "qr_code.created": "🔑",
    "qr_code.credited": "💸",
    "fund_account.validation.completed": "✅",
    "fund_account.validation.failed": "❌",
    "refund.speed_changed": "⚡",
    "refund.processed": "💸",
    "refund.failed": "❌",
    "refund.created": "📝",
    "transfer.processed": "💸",
    "transfer.failed": "❌",
    "account.instantly_activated": "⚡",
    "account.activated_kyc_pending": "📝",
    "account.under_review": "🔍",
    "account.needs_clarification": "❓",
    "account.activated": "✅",
    "account.rejected": "❌",
    "account.updated": "🔄",
    "payment_link.paid": "💰",
    "payment_link.partially_paid": "🔸",
    "payment_link.expired": "⏳",
    "payment_link.cancelled": "❌",
    "product.route.under_review": "🔍",
    "product.route.activated": "✅",
    "product.route.needs_clarification": "❓",
    "product.route.rejected": "❌",

    # New icons for API routes and related events
    "openapi.json": "📜",
    "swagger_ui_html": "📝",
    "swagger_ui_redirect": "🔄",
    "redoc_html": "📄",
    "index": "🏠",
    "register": "📝",
    "otpVerify": "🔑",
    "user.get": "👤",
    "user.update": "✏️",
    "user.delete": "🗑️",
    "choose_ticket": "🎫",
    "qr_code.create": "🔑",
    "qr_code.get": "📸",
    "qr_code.update": "🔄",
    "qr_code.delete": "🗑️",
    "razorpay_webhook": "🔗",
    "websocket_general_endpoint": "🌐",
    "websocket_realtime_endpoint": "📡",
    "websocket_otp_status_endpoint": "🔑",
    "websocket_session_endpoint": "💬",

    # User events (new)
    "user.signup": "👤",
    "user.logged_in": "🔑",
    "user.logged_out": "🚪",
    "user.deleted": "🗑️",
    "user.suspended": "⛔",

    # System events (new)
    "system.error": "⚠️",
    "system.maintenance": "🛠️",
    "system.reboot": "🔄",

    # Notification events (new)
    "notification.new": "🔔",
    "notification.read": "✅",
    "notification.deleted": "🗑️",

    # Miscellaneous (new)
    "search": "🔍",
    "help": "❓",
    "settings": "⚙️",
    "refresh": "🔄",
    "update": "🔄",
    "upload": "⬆️",
    "download": "⬇️",
    "lock": "🔒",
    "unlock": "🔓",
    "share": "🔗",
    "home": "🏠",
    "calendar": "📅",
    "message": "📩",
    "phone": "📱",
    "email": "📧",
    "location": "📍",
    "bell": "🔔",
    "success": "✅",
    "error": "⚠️",
    "warning": "⚠️",
    "info": "ℹ️",
    "question": "❓",
    "completed": "✔️",
    "failed": "❌",
    "new": "🆕",
    "edit": "✏️",
    "delete": "🗑️",
    "pause": "⏸️",
    "play": "▶️",
    "stop": "⏹️",
    "star": "⭐",
    "fire": "🔥",
    "thumb_up": "👍",
    "thumb_down": "👎",
    "pencil": "✏️",
    "check_mark": "✔️",
    "cross": "❌",
    "upload": "⬆️",
    "download": "⬇️",
    "refresh": "🔄",
    "lock": "🔒",
    "unlock": "🔓",
    "share": "🔗",
    "comment": "💬",
    "message": "📩",
    "phone": "📱",
    "email": "📧",
    "location": "📍",
    "bell": "🔔",
    "handshake": "🤝",
    "Existing": "📝 📂",
    "New": "➕",
    "role": "🔹"
}
