"""Initial migration

Revision ID: cc5a84ecc4ed
Revises: 
Create Date: 2025-02-16 22:37:08.062312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5a84ecc4ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('payments',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('ticket_description', sa.String(length=500), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('ticket_qty', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('transaction_fee', sa.Float(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total_tax', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('transaction_status', sa.Enum('successful', 'failed', 'processing', 'cancelled', 'due', name='payment_status'), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('qr_codes',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('payment_uuid', sa.String(length=36), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('qr_unique_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_uuid'], ['payments.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('qr_unique_id')
    )
    op.create_table('sms',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('payment_uuid', sa.String(length=36), nullable=True),
    sa.Column('qr_code_uuid', sa.String(length=36), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_uuid'], ['payments.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_code_uuid'], ['qr_codes.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('emails',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('payment_uuid', sa.String(length=36), nullable=True),
    sa.Column('qr_code_uuid', sa.String(length=36), nullable=True),
    sa.Column('sms_uuid', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_uuid'], ['payments.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_code_uuid'], ['qr_codes.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_uuid'], ['sms.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    op.drop_table('sms')
    op.drop_table('qr_codes')
    op.drop_table('payments')
    op.drop_table('users')
    # ### end Alembic commands ###
